# Requis par l'OpenThread Border Router (routage entre Thread et le LAN)
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1
# Garde l'IPv6 fonctionnel sur le Wi-Fi malgré le forwarding activé
net.ipv6.conf.wlp7s0.accept_ra=2
