# GDM configuration storage
# Auto-login: PC personnel sécurisé, utilisateur unique (jvzr)

[daemon]
AutomaticLoginEnable=True
AutomaticLogin=jvzr

[security]

[debug]
# Uncomment the line below to turn on debugging
#Enable=true
